// <auto-generated />
using System;
using System.Collections.Generic;
using AutomobiliuPardavimoPrograma.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutomobiliuPardavimoPrograma.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutomobiliuPardavimoPrograma.Models.Automobilis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aprasymas")
                        .HasColumnType("text");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<decimal>("Kaina")
                        .HasColumnType("numeric");

                    b.Property<string>("KuroTipas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Metai")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Nuotraukos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PavaruDeze")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Rida")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Automobiliai");
                });

            modelBuilder.Entity("AutomobiliuPardavimoPrograma.Models.UserPostLikes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPostLikes");
                });

            modelBuilder.Entity("AutomobiliuPardavimoPrograma.Models.Vartotojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ElPastas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlaptazodisHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("YraAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Vartotojai");
                });

            modelBuilder.Entity("AutomobiliuPardavimoPrograma.Models.UserPostLikes", b =>
                {
                    b.HasOne("AutomobiliuPardavimoPrograma.Models.Automobilis", "Automobilis")
                        .WithMany("UserPostLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomobiliuPardavimoPrograma.Models.Vartotojas", "Vartotojas")
                        .WithMany("UserPostLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automobilis");

                    b.Navigation("Vartotojas");
                });

            modelBuilder.Entity("AutomobiliuPardavimoPrograma.Models.Automobilis", b =>
                {
                    b.Navigation("UserPostLikes");
                });

            modelBuilder.Entity("AutomobiliuPardavimoPrograma.Models.Vartotojas", b =>
                {
                    b.Navigation("UserPostLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
